### PR TITLE
Create 111421-use-spoonacular-for-DB.md

### PR DESCRIPTION
**Pull request by MikeD-source**
Finish the first ADR which is the fact we are using Spoonacular API for database.

### CODE REVIEW

**Review by nabutabu — CHANGES_REQUESTED** [review]
Make sure the linting passes

**Comment by MikeD-source** [comment]
Hello, I got it fix. And I will add an adr about the changes we make for navbar as well.

**Comment by nabutabu** [comment]
Is this completed?

**Comment by MikeD-source** [comment]
> 

Yes, I think it is done.

**Review by nabutabu — APPROVED** [review]

**Pull request merged**
